
services:
  postgres:
    image: postgres:15
    container_name: kupipodariday-db
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
    container_name: kupipodariday-backend

    restart: always
    image: kirillgrom94/kupipodariday-backend:1.0.0
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: kupipodariday-frontend
    restart: always
    image: kirillgrom94/kupipodariday-frontend:1.0.0
    env_file:
      - ./frontend/.env
    ports:
      - '8081:80'
    depends_on:
      - backend

volumes:
  pgdata: